repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/squizlabs/PHP_CodeSniffer
    rev: 3.7.1
    hooks:
    -   id: phpcs
        args:
        - --standard=PSR12
        - --ignore=src/Kernel.php
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.2
    hooks:
    -   id: gitleaks-detect
