# Build stage
FROM python:3.9-slim-buster AS build

WORKDIR /app

COPY requirements.txt.tmpl .
RUN pip install --no-cache-dir -r requirements.txt.tmpl

COPY ./src .

# Final stage
FROM python:3.9-slim-buster

WORKDIR /app

COPY --from=build /app .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
