# Makefile for {{ .Project.Name }}

BINARY_NAME={{ .Project.Name }}

.PHONY: all deps clean build test run

all: build

deps:
	@echo "==> Installing dependencies..."
	go mod tidy

clean:
	@echo "==> Cleaning..."
	go clean
	rm -f $(BINARY_NAME)

build: deps
	@echo "==> Building binary..."
	go build -o $(BINARY_NAME) ./cmd/$(BINARY_NAME)/

test:
	@echo "==> Running tests..."
	go test ./...

run: build
	@echo "==> Running application..."
	./$(BINARY_NAME)
