# Build stage
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Final stage
FROM nginx:1.21.3-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
